Repository ectweitmann/book-club-ui, pull requests merged in 2022-02, with the labels that each got.

#1 Feature/initial component setup cr
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/App.js
  src/components/BookCard.js
  src/components/BookContainer.js
  src/components/BookDetails.js
  src/components/Favorites.js
  src/index.js
  src/styles/App.css
  src/styles/BookCard.css
  src/styles/BookContainer.css
  src/styles/BookDetails.css
  src/styles/Favorites.css
Labels: mvp

#2 Feature/home view cag
  package-lock.json
  src/components/App.js
  src/components/BookCard.js
  src/components/BookContainer.js
  src/components/BookDetails.js
Labels: mvp

#3 Feature/api calls krd
  src/apiCalls.js
  src/components/App.js
  src/utils.js
Labels: mvp

#8 Feature/testing all book display krd
  cypress.json
  cypress/fixtures/landingPageBooks.json
  cypress/integration/landing_page_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
Labels: mvp, testing

#13 Feature/book details page cag
  public/logo192.png
  public/logo512.png
  src/App.test.js
  src/components/BookDetails.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: mvp

#14 Feature/book details test cag
  cypress/fixtures/singleBook.json
  cypress/integration/book_details_spec.js
  src/components/BookDetails.js
Labels: mvp, testing

#19 Feature/grid display styling ect
  src/components/BookCard.js
  src/components/Nav.js
  src/index.css
  src/styles/App.css
  src/styles/BookCard.css
  src/styles/BookContainer.css
  src/styles/Nav.css
Labels: mvp

#20 Feature/book details view krd
  package-lock.json
  package.json
  src/apiCalls.js
  src/components/App.js
  src/components/BookCard.js
  src/components/BookContainer.js
  src/components/BookDetails.js
  src/styles/BookDetails.css
  src/utils.js
Labels: mvp

#22 Feature/displaying favorites ect
  public/index.html
  src/Book_Club_Logo.png
  src/components/App.js
  src/components/BookCard.js
  src/components/BookContainer.js
  src/components/BookDetails.js
  src/components/Error404.js
  src/components/Favorites.js
  src/components/Nav.js
  src/styles/App.css
  src/styles/BookCard.css
  src/styles/BookDetails.css
  src/styles/Error404.css
  src/styles/Favorites.css
  src/styles/Nav.css
Labels: mvp

#23 Patch/fix unique key prop error cag
  public/index.html
  public/manifest.json
  public/research-icon.png
  src/components/App.js
  src/components/BookCard.js
  src/components/BookContainer.js
  src/components/BookDetails.js
Labels: bug
